#!/usr/bin/env python3
"""Generate the typed mobile Studio job manifest from the server-owned JSON."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/facetta/studio_action_manifest.json"
TARGET = ROOT / "mobile/src/studio/generatedActionManifest.ts"


def render() -> str:
    manifest = json.loads(SOURCE.read_text(encoding="utf-8"))
    for action in manifest.values():
        for field in action["ui_schema"]:
            if "reference_role" in field:
                field["referenceRole"] = field.pop("reference_role")
    payload = json.dumps(manifest, indent=2, ensure_ascii=False)
    return (
        "/* Generated by scripts/generate_studio_action_manifest.py. */\n"
        "/* Do not edit this file directly. */\n"
        "import { StudioActionFieldDefinition, StudioAuthority, StudioLane, "
        "StudioOutputType } from './contracts';\n\n"
        "export interface StudioJobActionManifestEntry {\n"
        "  lane: StudioLane;\n"
        "  credits_per_output: number;\n"
        "  input_requirements: readonly string[];\n"
        "  context_requirements: readonly string[];\n"
        "  output_type: StudioOutputType;\n"
        "  authority: StudioAuthority;\n"
        "  ui_schema: readonly StudioActionFieldDefinition[];\n"
        "}\n\n"
        f"export const STUDIO_JOB_ACTION_MANIFEST = {payload} as const satisfies "
        "Record<string, StudioJobActionManifestEntry>;\n"
    )


if __name__ == "__main__":
    TARGET.write_text(render(), encoding="utf-8")
