#!/usr/bin/env python3
"""Generate the typed mobile Studio job manifest from the server-owned JSON."""

from __future__ import annotations

import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src/facetta/studio_action_manifest.json"
TARGET = ROOT / "mobile/src/studio/generatedActionManifest.ts"

EXECUTION_MODES = {
    "instant_transaction", "candidate_job", "terminal_job",
}
REVIEW_AUTHORITIES = {
    "none", "candidate_decision", "generic_transition",
}
REVIEW_AUTHORITY_BY_EXECUTION_MODE = {
    "instant_transaction": "none",
    "candidate_job": "candidate_decision",
    "terminal_job": "generic_transition",
}


def _validate_orchestration(action_id: str, action: dict) -> None:
    execution_mode = action.get("execution_mode")
    review_authority = action.get("review_authority")
    if execution_mode not in EXECUTION_MODES:
        raise ValueError(
            f"Studio action {action_id!r} has invalid execution_mode "
            f"{execution_mode!r}"
        )
    if review_authority not in REVIEW_AUTHORITIES:
        raise ValueError(
            f"Studio action {action_id!r} has invalid review_authority "
            f"{review_authority!r}"
        )
    expected_authority = REVIEW_AUTHORITY_BY_EXECUTION_MODE[execution_mode]
    if review_authority != expected_authority:
        raise ValueError(
            f"Studio action {action_id!r} execution_mode {execution_mode!r} "
            f"requires review_authority {expected_authority!r}"
        )


def render() -> str:
    manifest = json.loads(SOURCE.read_text(encoding="utf-8"))
    for action_id, action in manifest.items():
        _validate_orchestration(action_id, action)
        for field in action["ui_schema"]:
            if "reference_role" in field:
                field["referenceRole"] = field.pop("reference_role")
    payload = json.dumps(manifest, indent=2, ensure_ascii=False)
    return (
        "/* Generated by scripts/generate_studio_action_manifest.py. */\n"
        "/* Do not edit this file directly. */\n"
        "import { StudioActionFieldDefinition, StudioAuthority, "
        "StudioExecutionMode, StudioLane, StudioOutputType, "
        "StudioReviewAuthority } from './contracts';\n\n"
        "export interface StudioJobActionManifestEntry {\n"
        "  lane: StudioLane;\n"
        "  execution_mode: StudioExecutionMode;\n"
        "  review_authority: StudioReviewAuthority;\n"
        "  credits_per_output: number;\n"
        "  input_requirements: readonly string[];\n"
        "  context_requirements: readonly string[];\n"
        "  output_type: StudioOutputType;\n"
        "  authority: StudioAuthority;\n"
        "  ui_schema: readonly StudioActionFieldDefinition[];\n"
        "}\n\n"
        f"export const STUDIO_JOB_ACTION_MANIFEST = {payload} as const satisfies "
        "Record<string, StudioJobActionManifestEntry>;\n"
    )


if __name__ == "__main__":
    TARGET.write_text(render(), encoding="utf-8")
